### ISSUE TITLE
Can't find backward.hpp

### ISSUE THREAD

**Issue by stevechan1993** [WANG-KX/OpenChisel#2]
When I build this package,I got this error message:
/home/steve/catkin_ws/src/OpenChisel/chisel_ros/src/ChiselNode.cpp:21:24: fatal error: backward.hpp: 没有那个文件或目录

**Comment by tlb9551** [comment]
https://github.com/bombela/backward-cpp/blob/master/backward.hpp

**Comment by tlb9551** [comment]
> When I build this package,I got this error message:
> /home/steve/catkin_ws/src/OpenChisel/chisel_ros/src/ChiselNode.cpp:21:24: fatal error: backward.hpp: 没有那个文件或目录

https://github.com/bombela/backward-cpp/blob/master/backward.hpp

**Comment by WANG-KX** [comment]
Hi
Sorry for the code. Just remove the "backward.hpp" in every files, and remove "-lbfd" in every .cmake files.
