### ISSUE TITLE
No file 'chisel_msgs/ResetService.h'

### ISSUE THREAD

**Issue by Quitino** [WANG-KX/OpenChisel#3]
Hi, @WANG-KX .thank you  for your work,when I was build it,I encountered the error shown in the figure, and I also searched, and there was no such file. How to solve this problem, thank you very much.
![2019-12-04 10-04-33屏幕截图](https://user-images.githubusercontent.com/38552528/70106250-0abbed80-167e-11ea-9866-b5fc2224245c.png)

**Comment by Quitino** [comment]
My directory framework is shown in the figure. I found that my project was built incorrectly, but how do I build it?
![2019-12-04 10-39-29屏幕截图](https://user-images.githubusercontent.com/38552528/70107835-9e8fb880-1682-11ea-835a-1b789dd2ee94.png)

**Comment by tlb9551** [comment]
That's because the service file in chisel

**Comment by Quitino** [comment]
Thanks for your reply. I compiled ‘chisel_msgs’  and found ‘chisel_msgs / ResetService.h’ after compiling it separately. However, I cannot compile as a ROS project. How can I solve this problem? thank you very much.

**Comment by tlb9551** [comment]
try: catkin_make --only-pkg-with-deps chisel_msgs
then: catkin_make -DCATKIN_WHITELIST_PACKAGES = ""

Or just try: catkin_make -j1

**Comment by Quitino** [comment]
Thanks for your reply, this method not work. It needs to compile the header file to the path shown in the figure.But it compiled out empty.
![2019-12-04 11-53-10屏幕截图](https://user-images.githubusercontent.com/38552528/70111442-1f53b200-168d-11ea-8b33-0dff49a7f9dc.png)

**Comment by Quitino** [comment]
I copied it and recompiled it, and it seemed to be correct ('make’ with 0 errs). Thank you very much for your reply.
